# Default configuration
email: ""
domain_id: ""
slam_ip: "127.0.0.1"
slam_port: 1448
timeout_ms: 1000

# Domain Configuration
domain:
  raycast_endpoint: "https://dsc.dev.aukiverse.com/spatial/raycast"
  map_endpoint: "https://dsc.dev.aukiverse.com/spatial/crosssection"
  navmesh_endpoint: "https://dsc.dev.aukiverse.com/spatial/restricttonavmesh"
  #domain_server: "https://ap-east-1.domains.prod.aukiverse.com"

# Home Dock Position [x, y, z, yaw, pitch, roll]
homedock: [0.1036, 1.869, 0, 3.111, 0, 0]

patrol:
  point1: [-1.14, 2.21, 3.14]
  point2: [-6.11, 2.35, -1.57]
  point3: [-6.08, 0.05, 0]
  point4: [-1.03, 0.01, 1.57]  

speeds:
  patrol: "0.25"
  product_search: "0.7"
  default: "0.5"

gotu:
  endpoint: "https://conference-backend-0.aukiverse.com/api/collections/Node/records?page=1&perPage=500&skipTotal=1&filter=Domain%3D%228093f9bf-c374-4162-ab74-ab61949627f1%22&fields=Name,Description,Pose,Image,id"
  image_download_endpoint: "https://conference-backend-0.aukiverse.com/api/files/gkzgdbw8bnw0bs7/{id}/{Image}"

series_move_to:
  - [-1.14, 2.21, 3.14]
  - [-3.14, 2.21, 3.14]
  - [-6.11, 2.35, -1.57]
  - [-6.11, 1.35, -1.57]
  - [-6.08, 0.05, 0]
  - [-3.08, 0.05, 0]
  - [-1.03, 0.01, 1.57]